### ISSUE TITLE
Database Download no longer works

### ISSUE THREAD

**Issue by zslastman** [seandavi/GEOmetadb#3]
Hi guys, the dropbox link your package tries to download from is dead now:

https://dl.dropboxusercontent.com/u/51653511/GEOmetadb.sqlite.gz

**Comment by seandavi** [comment]
Yes, sorry for the confusion. The database has grown to the point that we could no longer host it on dropbox, so we transitioned to a new URL on Amazon. Just update to the newest GEOmetadb version for the new download functionality. If you just want the URL, see the code here:

https://github.com/seandavi/GEOmetadb/blob/master/R/getSQLiteFile.R

**Comment by zslastman** [comment]
Perfect, thanks a million for the swift response!
